spring:
  application:
    name: noorschool-back

  config:
    import: optional:classpath:application-private.yml

server:
  port: ${PORT:10000}
  address: 0.0.0.0

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.noorschool
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.noorschool: debug